### ISSUE TITLE
Facebook login emailVerified false

### ISSUE THREAD

**Issue by WeiWang120** [adrien2p/medusa-plugins#100]
I've setup both google and facebook login with the auth plugin, however I observed that upon customer creation, for facebook the metadata is `{"authProvider": "facebook.store.medusa-auth-plugin", "emailVerified": false, "useSocialAuth": true}`

For google it's `{"authProvider": "google.store.medusa-auth-plugin", "emailVerified": true, "useSocialAuth": true}`

What leads to the difference in emailVerified? Both of them actually have access to the email address.

**Comment by adrien2p** [comment]
this is only the result of this : `profile._json.email_verified`

**Comment by adrien2p** [comment]
Could you try the latest please and report back if anything goes wrong
