### ISSUE TITLE
google auht redirect

### ISSUE THREAD

**Issue by uzairusman1425** [adrien2p/medusa-plugins#109]
after google authentication i am getting redirect to this page instead of my  storefront 
![redirect](https://github.com/adrien2p/medusa-plugins/assets/126361186/f0d3a433-348a-4244-973f-f9a9b4388182)

**Comment by adrien2p** [comment]
looks like the provider does not exists in your passport. This often happen when the version of passport is different from the one used by medusa, then the provider are not stored in the same passport instance. Can you share the versions of your packages please

**Comment by uzairusman1425** [comment]
![Uploading version.png…]()

**Comment by uzairusman1425** [comment]
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Sebastian Rindom <skrindom@gmail.com>",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "clean": "cross-env ./node_modules/.bin/rimraf dist build .cache",
    "build": "cross-env npm run clean && npm run build:server ",
    "build:server": "cross-env npm run clean && tsc -p tsconfig.server.json",
    "build:admin": "cross-env medusa-admin build ",
    "watch": "cross-env tsc --watch",
    "test": "cross-env jest",
    "seed": "cross-env medusa seed -f ./data/products_seed.json",
    "start": "cross-env npm run build && medusa start",
    "start:custom": "cross-env npm run build && node --preserve-symlinks index.js",
    "dev": "cross-env npm run build:server && medusa develop"
  },
  "dependencies": {
    "@medusajs/admin": "^7.0.1",
    "@medusajs/cache-inmemory": "1.8.8",
    "@medusajs/cache-redis": "1.8.8",
    "@medusajs/event-bus-local": "1.9.6",
    "@medusajs/event-bus-redis": "1.8.9",
    "@medusajs/file-local": "^1.0.1",
    "@medusajs/medusa": "^1.15.1",
    "@tanstack/react-query": "^4.32.6",
    "axios": "^1.5.1",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "dotenv": "^16.1.4",
    "express": "^4.17.2",
    "medusa-file-minio": "^1.2.2",
    "medusa-file-spaces": "^1.4.0",
    "medusa-fulfillment-manual": "^1.1.37",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.23",
    "medusa-payment-stripe": "^6.0.0",
    "medusa-plugin-auth": "^1.7.0",
    "medusa-react": "^9.0.4",
    "paytabs_pt2": "^2.0.8",
    "typeorm": "^0.3.16"
  },
  "devDependencies": {
    "@babel/cli": "^7.14.3",
    "@babel/core": "^7.14.3",
    "@babel/preset-typescript": "^7.21.4",
    "@medusajs/medusa-cli": "1.3.20",
    "@types/express": "^4.17.13",
    "@types/jest": "^27.4.0",
    "@types/node": "^17.0.8",
    "babel-preset-medusa-package": "^1.1.13",
    "cross-env": "^7.0.3",
    "eslint": "^6.8.0",
    "jest": "^27.3.1",
    "mongoose": "^5.13.14",
    "rimraf": "^3.0.2",
    "ts-jest": "^27.0.7",
    "ts-loader": "^9.2.6",
    "typescript": "^4.5.2"
  },
  "jest": {
    "globals": {
      "ts-jest": {
        "tsconfig": "tsconfig.spec.json"
      }
    },
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "testPathIgnorePatterns": [
      "/node_modules/",
      "<rootDir>/node_modules/"
    ],
    "rootDir": "src",
    "testRegex": "(/__tests__/.*|\\.(test|spec))\\.(ts|js)$",
    "transform": {
      ".ts": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "./coverage",
    "testEnvironment": "node"
  }
}

**Comment by adrien2p** [comment]
Somehow the strategy are not present in passport, is there any logs that can be of use? Maybe just to be absolutely sure, can you check that an error is not swallowed somewhere in the node_modules/@medusajs/medusa/dist/loaders/plugins. I ve teated ut lately and everything was working

**Comment by uzairusman1425** [comment]
this is my **cofing** 


const dotenv = require("dotenv");

let ENV_FILE_NAME = "";
switch (process.env.NODE_ENV) {
  case "production":
    ENV_FILE_NAME = ".env.production";
    break;
  case "staging":
    ENV_FILE_NAME = ".env.staging";
    break;
  case "test":
    ENV_FILE_NAME = ".env.test";
    break;
  case "development":
  default:
    ENV_FILE_NAME = ".env";
    break;
}

try {
  dotenv.config({ path: process.cwd() + "/" + ENV_FILE_NAME });
} catch (e) { }

// CORS when consuming Medusa from admin
const ADMIN_CORS =
  process.env.ADMIN_CORS || "http://localhost:7000,http://localhost:7001";

// CORS to avoid issues when consuming Medusa from a client
const STORE_CORS = process.env.STORE_CORS || "http://localhost:3000";

const DATABASE_URL =
  process.env.DATABASE_URL || "postgres://localhost/medusa-store";

const REDIS_URL = process.env.REDIS_URL || "redis://localhost:6379";

const BACKEND_URL = process.env.BACKEND_URL || "http://localhost:9000"
const ADMIN_URL = process.env.ADMIN_URL || "http://localhost:7001"
const STORE_URL = process.env.STORE_URL || "http://localhost:3000"

const GoogleClientId = process.env.GOOGLE_CLIENT_ID || "1030979777125-lsdsrd2qk7rh11b9cesuc9dfpthpmbfc.apps.googleusercontent.com"
const GoogleClientSecret = process.env.GOOGLE_CLIENT_SECRET || "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"




const plugins = [
  `medusa-fulfillment-manual`,
  `medusa-payment-manual`,
  {
    resolve: `@medusajs/file-local`,
    options: {
      upload_dir: "uploads",
    },
  },
  // To enable the admin plugin, uncomment the following lines and run `yarn add @medusajs/admin`
  {
    resolve: "@medusajs/admin",
    /** @type {import('@medusajs/admin').PluginOptions} */
    options: {

      autoRebuild: true,
      serve: true,
    },
  },
  {
    resolve: `medusa-file-spaces`,
    options: {
      spaces_url: process.env.SPACE_URL,
      bucket: process.env.SPACE_BUCKET,
      endpoint: process.env.SPACE_ENDPOINT,
      access_key_id: process.env.SPACE_ACCESS_KEY_ID,
      secret_access_key: process.env.SPACE_SECRET_ACCESS_KEY,
    },
  },
  // {
  //   resolve: `medusa-merchant-apis`,
  //   options: {},
  // },


  {

    resolve: "medusa-plugin-auth",
    /** @type {import('medusa-plugin-auth').AuthOptions} */
    options: {

      google: {
        clientID: GoogleClientId,
        clientSecret: GoogleClientSecret,

        admin: {
          callbackUrl: `${BACKEND_URL}/admin/auth/google/cb`,
          failureRedirect: `${ADMIN_URL}/login`,
          successRedirect: `${ADMIN_URL}/`,
        },

        store: {
          callbackUrl: `${BACKEND_URL}/store/auth/google`,
          failureRedirect: `${STORE_URL}/login`,


          successRedirect: `${STORE_URL}/`,


        }
      }
    }
  }




];

const modules = {
  /*eventBus: {
    resolve: "@medusajs/event-bus-redis",
    options: {
      redisUrl: REDIS_URL
    }
  },
  cacheService: {
    resolve: "@medusajs/cache-redis",
    options: {
      redisUrl: REDIS_URL
    }
  },*/
};

/** @type {import('@medusajs/medusa').ConfigModule["projectConfig"]} */
const projectConfig = {
  jwtSecret: process.env.JWT_SECRET,
  cookieSecret: process.env.COOKIE_SECRET,
  store_cors: STORE_CORS,
  database_url: DATABASE_URL,
  admin_cors: ADMIN_CORS,
  // Uncomment the following lines to enable REDIS
  // redis_url: REDIS_URL
};

/** @type {import('@medusajs/medusa').ConfigModule} */
module.exports = {
  projectConfig,
  plugins,
  modules,
};

**Comment by uzairusman1425** [comment]
> Can you also share tour config please.

evertihng is runnig when i used the admin i get redirected to admin but on the user i got this this error only

**Comment by adrien2p** [comment]
Aren't you missing /cb on your store callback?

**Comment by uzairusman1425** [comment]
![image](https://github.com/adrien2p/medusa-plugins/assets/126361186/b81780aa-df35-46a7-b0c6-962bd19283c9)

**Comment by uzairusman1425** [comment]
![image](https://github.com/adrien2p/medusa-plugins/assets/126361186/10a5da5e-43e4-4229-9528-275ea45a7fc9)
only issue is with redirect. user is created

**Comment by adrien2p** [comment]
I ll have a look at that asap

**Comment by adrien2p** [comment]
Would you be able to downgrade the plugin and test?

**Comment by rana0045** [comment]
> Would you be able to downgrade the plugin and test? Just to see if the changes are the cause

same issue

**Comment by adrien2p** [comment]
will be fixed in the next release normally 💪
