### ISSUE TITLE
strict config doesn't seem to work with 1.8.1

### ISSUE THREAD

**Issue by tsvetann** [adrien2p/medusa-plugins#113]
After upgrading to medusa-plugin-auth@1.8.1 the strict config is not working at more. I have strict=none in my app and I still got the message=Guest customer with email already exists. Has anything changed regarding strict config in the latest version?

Here is how I use it:
```
{
    resolve: "medusa-plugin-auth",
    /** @type {import('medusa-plugin-auth').AuthOptions} */
    options: {
      strict: "none",
      google: {
```

Thanks

**Comment by adrien2p** [comment]
weird nothing has changed in that regards, I ll check that tomorrow

**Comment by tsvetann** [comment]
> weird nothing has changed in that regards, I ll check that tomorrow

I had a quick look and it seems to be here:                                                                 [passportCallbackAuthenticateMiddlewareOptions.failureRedirect + '?message=' + options.msg](https://github.com/adrien2p/medusa-plugins/blob/03f4f1e292c41857e23326cab281d3ed4d3eb808/packages/medusa-plugin-auth/src/core/passport/utils/auth-routes-builder.ts#L102)

**Comment by adrien2p** [comment]
not sure, cause the callback is already completed at that moment and already thrown the error that we access here

**Comment by adrien2p** [comment]
Just tested, and I get the strict properly set to the correct value I have in my config, so nothing should have changed in your behavior

<img width="846" alt="Screenshot 2023-11-16 at 14 23 18" src="https://github.com/adrien2p/medusa-plugins/assets/25098370/b00dee4e-5a47-49b6-a38a-5c67595d61d1">

**Comment by adrien2p** [comment]
I think the error you are getting comes from medusa and not the plugin itself, what I think is happening is that you have a guest customer created who didn't validate their account. therefore, the retreiveRegisteredAccount doesn't returns it and the customer is being created which is not allowed if a guest customer already exists in medusa

**Comment by tsvetann** [comment]
I could be totally wrong here but when a user creates an order in medusa without registering, medusa creates a guest customer (and as far as I've seen this is the only way to end up as a guest customer). If the same user later on decides to register an account in medusa, the backend creates a second account (with the same email) and has_account is set to true. My understanding was that medusa determines if account exists not just by email but by email + has_account. So if we assume that there is already a guest customer in the system, when the same user tries to login with google (for example), shouldn't we allow that customer to actually have a second account by setting has_account=true?

Thanks
