### ISSUE TITLE
Steam login - feature

### ISSUE THREAD

**Issue by piereligio** [adrien2p/medusa-plugins#117]
Hi, I'm working on a digital products store using Medusa. 
I'd like to add Steam login/signup. 
I've seen there is node-steam-openid, and I was thinking of integrating this on this plugin. But honestly, I don't have the necessary knowledge yet. 
I think it's not difficult to do, is it possible to add it as a feature here? 
EDIT: there also is passport-steam, which makes it very easy considering current implementation of the others, like facebook.

I know it's pretty niche, so, if it's not possible, what's the general approach I should use to do it myself? 
I know how to install and set up plugins regularly, but I don't know how to do that for a plugin of which I have the source code in my disk, and I'd like tinkering with.

Thanks in advance.

**Comment by adrien2p** [comment]
should we close this one in the mean time?
