### ISSUE TITLE
Unauthorized after updating to 1.8.2

### ISSUE THREAD

**Issue by hampusboas** [adrien2p/medusa-plugins#122]
Hi, i updated to the latest version. 
But when i go to the endpoint /store/auth/ to get the current customer object.
It returns 401 Unauthorized.

The user is successfully created and returns the cookie credentials when using the firebase auth. But the returned cookie is not valid for use in any store endpoints.

Best regards.

**Comment by hampusboas** [comment]
I'm running the latest version of medusa v1.18.1.

**Comment by adrien2p** [comment]
Humm, ok so to summarise you are using firebase auth, latest auth plugin and medusa 1.18.1

@dPreininger can I get you to have a look at this one please ☺️ would be wonderful

**Comment by dPreininger** [comment]
Ill take a look

**Comment by Slaknoah** [comment]
Not sure its related but it seams 1.8.2 build only includes the core folder, I had to revert to 1.8.1

**Comment by adrien2p** [comment]
you are right, that is weird, I ve just published 1.8.3, it should include everything. Could you give it a try please

**Comment by Slaknoah** [comment]
It works now thank you!

**Comment by hampusboas** [comment]
Great job! It works! Tank you!

**Comment by adrien2p** [comment]
Thanks to @Slaknoah for spotting this bad boy 😂

**Comment by kevinrobert3** [comment]
Been scouring around for a solution to my issue and found this issue. This is similar to this issue https://github.com/adrien2p/medusa-plugins/issues/149#issue-2181524796    am on v1.20.2
