### ISSUE TITLE
Update documentation for new plugin options configuration

### ISSUE THREAD

**Issue by adrien2p** [adrien2p/medusa-plugins#126]
@stephane-segning would you like to give a try to the doc pr? ❤️

**Comment by stephane-segning** [comment]
Sure! I already started anyway. Can you create the ticket for that, so that
we know that I'm it?

**Comment by adrien2p** [comment]
ahah you rock man 🚀

**Comment by adrien2p** [comment]
Any news? 😇 @stephane-segning

**Comment by stephane-segning** [comment]
Yeah. I’ll be doing a push by tomorrow afternoon, work is no easy before
holidays 🤣

**Comment by adrien2p** [comment]
Ahah take you time if you have deadlines man 👍 appreciate the work you are putting in it already 🙏

**Comment by adrien2p** [comment]
@stephane-segning hope you had a wonderful time. when do you think you could handle this one ?

**Comment by adrien2p** [comment]
I ve pushed a new version including the new options shape under 1.9.0, lets get the doc next 👍

**Comment by adrien2p** [comment]
Just to let you know, we can handle async option loading since the route loader in medusa does not accept a promise leading to some errors, we can re look at that at a later time

**Comment by adrien2p** [comment]
@stephane-segning it is being handled by another contributor. thanks a lot for your contribution
