### ISSUE TITLE
Apple login method 

### ISSUE THREAD

**Issue by luluhoc** [adrien2p/medusa-plugins#130]
Have you considered adding apple login method?

**Comment by adrien2p** [comment]
No, but pr's are welcome 🙏

**Comment by luluhoc** [comment]
@adrien2p I will make a PR for sure. Can i change also the documentation so it reflects the new config?

**Comment by adrien2p** [comment]
Yes that would be wonderful, i was waiting for another contributor to do it as he wanted to do it but he might not be available at the moment. You can do it and then ill review it.

**Comment by luluhoc** [comment]
@adrien2p I will make a PR soon, meanwhile I'm trying to run it in docker and I'm getting

```
Error: Unknown authentication strategy "google.store.medusa-auth-plugin_google"
    at attempt (/app/medusa/node_modules/passport/lib/middleware/authenticate.js:193:39)
    at authenticate (/app/medusa/node_modules/passport/lib/middleware/authenticate.js:370:7)
    at Layer.handle [as handle_request] (/app/medusa/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/medusa/node_modules/express/lib/router/route.js:144:13)
    at /app/medusa/node_modules/medusa-plugin-auth/core/passport/utils/auth-routes-builder.js:39:9
    at Layer.handle [as handle_request] (/app/medusa/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/medusa/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/app/medusa/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/app/medusa/node_modules/express/lib/router/layer.js:95:5)
    at /app/medusa/node_modules/express/lib/router/index.js:284:15

```

Do you have any idea what can be causing this? Local works...

**Comment by adrien2p** [comment]
Unfortunately i don't know, maybe a dependency issue in docker? In general if passport does not find the strategy it can either be that the plugin did not load or that the passport package used by medusa and the package defer and therefore it does not get registered to the same passport instance

**Comment by luluhoc** [comment]
@adrien2p Thanks, I'm getting these in logs

by the way are the types in the auth package changed to new config?

```
INF Registering custom endpoints for medusa-plugin-auth | activity_id=01HKNC2NK4ZV17FEX8146BMX4E timestamp=2024-01-08 20:26:31
INF Registering custom endpoints for medusa-plugin-auth | activity_id=01HKNC2NK2ATJQ9G1J8B00XF1B timestamp=2024-01-08 20:26:31

WRN Running loader failed: OAuth2Strategy requires a clientID option | timestamp=2024-01-08 20:26:32
WRN Running loader failed: OAuth2Strategy requires a clientID option | timestamp=2024-01-08 20:26:32
```

**Comment by luluhoc** [comment]
> Unfortunately i don't know, maybe a dependency issue in docker? In general if passport does not find the strategy it can either be that the plugin did not load or that the passport package used by medusa and the package defer and therefore it does not get registered to the same passport instance

Sorry it was my fault, I forgot to add to the env client and secret id
