### ISSUE TITLE
social login returns {"exist": false} 

### ISSUE THREAD

**Issue by Nadeem34513** [adrien2p/medusa-plugins#134]
I'm trying to integrate google and facebook sign ups and whenever I hit the auth path, I get this response:
`{ "exists": false }`

It was working well back in November, haven't updated the package or changed any config in google cloud platform or meta developer account
**System information**

Medusa version (including plugins): v1.17.4
medusa-plugin-auth: v1.8.3

[![Screenshot (313)](https://github.com/adrien2p/medusa-plugins/assets/65117082/5da01309-e4ee-44fc-8bc7-316a0c9d7291)](url)

![Screenshot 2024-01-10 151137](https://github.com/adrien2p/medusa-plugins/assets/65117082/6feae077-2024-4282-94d1-82ffd8f6b1cc)

**Comment by adrien2p** [comment]
Can you upgrade your auth package version please. I will soon deploy the updated doc as well

**Comment by Nadeem34513** [comment]
I have updated the auth package to `v1.9.1` and still the same error occurs.

**Comment by Nadeem34513** [comment]
@adrien2p , how you please help me on this?

**Comment by gempain** [comment]
Had the same issue. I was in `1.11.0` and upgraded to `1.11.1` and it solved the issue. I have dug much but my intuition is that the `exists: false` is throw by Medusa, not by the plugin. Why is a mystery.
