### ISSUE TITLE
Adding Google Authentication to the store: Am I missing something?

### ISSUE THREAD

**Issue by Saadchr** [adrien2p/medusa-plugins#139]
- Hi , implementing a google Authentication is a new thing for me, so, here all the steps I went through to implement an authentication for the store

    1. Installing the plugin  with yarn add medusa-plugin-auth.
    
    2. Setting the variables 
    ```
        - const BACKEND_URL = process.env.BACKEND_URL || "localhost:9000";
        - const STORE_URL = "https:://localhost:8000";  I set this to localhost:8000 as I am testing the authentication on the local store.
        - const GoogleClientId = process.env.GOOGLE_CLIENT_ID || "";  
        - const GoogleClientSecret = process.env.GOOGLE_CLIENT_SECRET || "";  
        ```
        
        
    4. Setting the configuration as it's written in the documentation
        ```
         options: [
      {
        type: "google",
        // strict: "all", // or "none" or "store" or "admin"
        strict: "none",
        identifier: "google",
        clientID: GoogleClientId,
        clientSecret: GoogleClientSecret,
        store: {
          callbackUrl: `${BACKEND_URL}/store/auth/google/cb`,
          failureRedirect: `${STORE_URL}/login`,
          // The success redirect can be overriden from the client by adding a query param `?redirectTo=your_url` to the auth url
          // This query param will have the priority over this configuration
          successRedirect: `${STORE_URL}/`,
          authPath: "/store/auth/google",
          // authCallbackPath: "/store/auth/google/cb",
          // expiresIn: 24 * 60 * 60 * 1000,
          // verifyCallback: (container, req, accessToken, refreshToken, profile, strict) => {
          //    // implement your custom verify callback here if you need it
          // },
          scope: [`email`, `profile`],
        },
      },
    ],
  },
```

  
    5. Google Cloud Developer
        - Set up my credentials
        - Set up my redirect url: Has it to be the callbackUrl or the successRedirect? This is what I've done
        
    6. Setting The login button in the client side
        ```
        <a type="button"
          href="https://medusa14-production.up.railway.app/store/auth/google/" 
          className="text-white bg-[#4285F4] hover:bg-[#4285F4]/90 focus:ring-4 focus:outline-none focus:ring-[#4285F4]/50 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:focus:ring-[#4285F4]/55 mr-2 mb-2"
        >
        ```
        
        
        
###     6. My questions are the following:

        - Shoud the href of the button correspond to the authPath of the plugin 
        - Should be the the redirectUrl equal to the callbackUrl or to the successRedirect?
        - Clicking on the button currently doesn't login the user, it triggers these requests:
        
 Request URL:
https://medusa14-production.up.railway.app/store/auth/google/
Request Method:
GET
Status Code:
302 Found
Failed to load response data: No
content available because this
request was redirected 

Request URL:
https://accounts.google.com/o/oauth2/v2/auth?response_type=code&redirect_uri=https%3A%2F%2Fmedusa14-production.up.railway.app%2Fstore%2Fauth%2Fgoogle%2Fcb&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&client_id=748180994839-a0uetc4gj7qj3bn5u6evctcr9dhkm99i.apps.googleusercontent.com
Request Method:
GET
Status Code:
302 Found
Failed to load response data: No
content available because this
request was redirected 
            - https://medusa14-production.up.railway.app/store/auth/google/cb?code=4%2F0AfJohXnaYXvsaKX71HhEVBvPVX7x4VH6BCohixOtvP-eFF6eGUMXE_ngeadcij-zG552JQ&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&authuser=0&prompt=none
            
            
            
Request Method:
GET
Status Code:
302 Found
Failed to load response data: No
content available because this
request was redirected 

This one is highlighted in red
localhost:8000/?access_token=dummydataxxx
Failed to load response data: No
resource with given identifier found

Thanks for helping me out

**Comment by adrien2p** [comment]
just putting the discord discussion here for ref https://discord.com/channels/876835651130097704/1205582972653142056

**Comment by adrien2p** [comment]
Fixed as per the linked discussion
