### ISSUE TITLE
medusa-plugin-sentry > Admin UI routing support for latest version

### ISSUE THREAD

**Issue by Enalmada** [adrien2p/medusa-plugins#140]
The [documentation for adding sentry to admin-ui](https://medusa-plugins.vercel.app/sentry/admin-ui) says 
```
Open the src/pages/a.js
Next, add the following code to the Routes component...
```

I don't seem to have a pages directory, just a src/admin/routes as defined [here](https://docs.medusajs.com/admin/routes).   I don't seem to have a Routes component.  I am very new to medusa and could be wrong but I suspect the way medusa is routing has changed since this module was released?  Could medusa-plugin-sentry admin ui documentation be updated to support latest current medusa?

Thanks for your help.

versions
```
    "@medusajs/admin": "^7.1.9",
    "@medusajs/medusa": "^1.7.0",
    "@medusajs/ui": "^2.2.0",
    "@medusajs/ui-preset": "1.0.2",
```

**Comment by adrien2p** [comment]
Indeed it would require to be migrated to the new admin custom ui component. I don't have the time at the moment but PR are welcome
