### ISSUE TITLE
[medusa-plugin-prometheus] dependency issue, not able to install

### ISSUE THREAD

**Issue by kaisiant** [adrien2p/medusa-plugins#146]
<img width="702" alt="image" src="https://github.com/adrien2p/medusa-plugins/assets/26655111/d3f49d6c-9359-4ed4-a983-f99fc8e25b3a">

**Comment by adrien2p** [comment]
Ill have a look asap, in the mean time you can force it

**Comment by adrien2p** [comment]
After looking at the deps, it seems to be an issue with the medusa plugins, not this one. I ll close until further information
