### ISSUE TITLE
Cors Issue in Production, Firebase Auth

### ISSUE THREAD

**Issue by kevinrobert3** [adrien2p/medusa-plugins#153]
Everything works perfectly in localhost but on deploying to vercel, we get cors error 
![Screenshot 2024-03-23 at 01 55 54](https://github.com/adrien2p/medusa-plugins/assets/12913275/ef25e13f-9e4b-43a7-ba03-bc2247d5bd92)
This is our staging subdomain e.g staging.plugin.com, our preview urls also have the same cors error. We have added the regex for vercel.app and our subdomain to store cors. 
This (/admin/auth/firebase) is the only api that has the cors error

**Comment by kevinrobert3** [comment]
I have managed to fix it in the staging subdomain. But all .vercel.app urls have the cors error. 
This is my ADMIN_CORS
const ADMIN_CORS=`http://localhost:7000,http://localhost:7001,http://localhost:3000,https://staging.plugin.com,/vercel\\.app$/`;

**Comment by adrien2p** [comment]
Have you checked if it is part of the domain public list? Cause those domains will never pass if they are part of the list for security reasons, otherwise anybody with a public domain could access yours

**Comment by adrien2p** [comment]
Any news?

**Comment by kevinrobert3** [comment]
Hello Adrienne, welcome back, I managed to fix this i.e the `admin/auth/firebase` route. I can close this issue now. 

Outside of this issue, can you take a quick glance at this issue https://github.com/medusajs/medusa/issues/6809 if in your core focus at Medusa and maybe shed light. It is a cors error issue but affecting certain routes only. It is quite bizarre and I was told it is a misconfiguration.
