### ISSUE TITLE
Google Auth login get "Missing required parameter: scope Learn more about this error" 

### ISSUE THREAD

**Issue by yunfengsay** [adrien2p/medusa-plugins#158]
![image](https://github.com/adrien2p/medusa-plugins/assets/15527378/a3d99e16-c638-4789-9fd5-ff283e1e13f0)
![image](https://github.com/adrien2p/medusa-plugins/assets/15527378/9779d69d-a345-4a04-83bb-da66b2210e94)
Where should  I config scope ?

**Comment by adrien2p** [comment]
the scope is not configurable, it looks more like miss usage to me, can you comment your verify callback if there is not custom implementation, also, what url is your client calling when you click your button to login with googld?

**Comment by yunfengsay** [comment]
> the scope is not configurable, it looks more like miss usage to me, can you comment your verify callback if there is not custom implementation, also, what url is your client calling when you click your button to login with google?

You are right, I had set error url for my login button, the url before is /store/auth/google/cb , but the correct is /store/auth/google . After I removed /cb  , it works well now.
