### ISSUE TITLE
Bump Sentry packages

### ISSUE THREAD

**Issue by pepijn-vanvlaanderen** [adrien2p/medusa-plugins#159]
Currently the Sentry plugin uses older version of Sentry Node. If you use a monorepo with Next, you could get duplicate sentry node packages and then the medus sentry plugin throws errors, like `TypeError: request.headers.split is not a function`.

Could you bump the package version? In the meantime I add a resolution in my root package.json:
```
  "resolutions": {
    "@sentry/core": "latest",
    "@sentry/node": "latest",
    "@sentry/types": "latest",
    "@sentry/utils": "latest",
    ...
  },
```

**Comment by adrien2p** [comment]
Hi, i will handle that but i wont be able for the next two weeks unfortunately as i am without my laptop, hope you understand, after that ill do the update 💪

**Comment by adrien2p** [comment]
will push in the next release 👍
