### ISSUE TITLE
Add environment to configuration

### ISSUE THREAD

**Issue by DoubleOTheven** [adrien2p/medusa-plugins#162]
Please add a feature where we can pass in the environment as a Sentry tag so that we can filter Sentry logs by each tag and keep all logs under a single Sentry project. [See docs here](https://docs.sentry.io/product/sentry-basics/concepts/environments/).

**Comment by adrien2p** [comment]
will push in the next release 👍

**Comment by vavilondev** [comment]
@adrien2p for now there is only prod env?

**Comment by ehimah** [comment]
hey @adrien2p  any update on this? I believe this fix is a one-liner, if we get rid of [this line](https://github.com/adrien2p/medusa-plugins/blob/main/packages/medusa-plugin-sentry/src/api/index.ts#L25), then the `environment` plugin option will be fed into the `Sentry.init()` call.

Let me know, and I can send a PR your way 🙏🏽
