### ISSUE TITLE
Question about “Firebase” 

### ISSUE THREAD

**Issue by KareemAbbas1** [adrien2p/medusa-plugins#171]
I'm building a medusajs backend+dashboard. The backend will be used by multiple frontends(e.g web, mobile). My first question is in my Firebase project I have to create an app in order to use the authentication service so do I have to create three apps for each frontend(web, iOS, android)?
The second thing that is the reason for this query is what exactly is CredentialJsonPath. I'm mean what should I provide to medusajs in order to connect it to my Firebase project(e.g the authDomain)?

**Comment by hunglmtb** [comment]
CredentialJsonPath is path to private key of your firebase project which is possible created at https://console.firebase.google.com (in project setting -> service accounts then create of use the exist one). This is used for the plugin at back-end
sample of the key:
`

{
  "type": "service_account",
  "project_id": "ID",
  "private_key_id": "0e5086...",
  "private_key": "-----BEGIN PRIVATE KEY-----CONTENT-----END PRIVATE KEY-----\n",
  "client_email": "firebase-adminsdk-XYZ@XYZ.iam.gserviceaccount.com",
  "client_id": "1048XYZ",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-XYZ%40XYZ.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}

`

> My first question is in my Firebase project I have to create an app in order to use the authentication service so do I have to create three apps for each frontend(web, iOS, android)? 

you should create 3 apps at your project on firebase console: ios, android, web and use the config for mobile app or web such as `firebaseConfig ` for web and` google-services.json` for mobile app. they are used at front-end

Sorry for any misunderstanding
