### ISSUE TITLE
How can i integrate firebase auth with Medusa?

### ISSUE THREAD

**Issue by balramxyadav** [adrien2p/medusa-plugins#174]
I tried to use the Medusa Auth plugin to authenticate with Firebase but couldn't get it to work. Could anyone guide me on how to implement it correctly?

I followed the documentation and configured the plugin in the backend, including adding the Firebase service account credentials.

Then, I integrated Firebase with NextAuth on the frontend and tried passing the access token to the Medusa backend at /store/auth/firebase. However, I encountered the following error: 'Unknown authentication strategy "firebase.store.medusa-auth-plugin_firebase"

**Comment by adrien2p** [comment]
Often it can be either configuration issue or two different versions of passport in your node modules
