### ISSUE TITLE
Logout 

### ISSUE THREAD

**Issue by EgorSaffrezzi** [adrien2p/medusa-plugins#175]
Cool lib, where there is not a word about how to log out a person after he has successfully logged in via Google.

Is not working... 

cookies().set("_medusa_jwt", "", {
    maxAge: -1,
  })
  
  
  
Describe in human terms how to implement the basic points of your library

**Comment by shubhamchoudhary-2003** [comment]
hi bro can we talk

**Comment by EgorSaffrezzi** [comment]
@shubhamchoudhary-2003  I fixed it, thanks !
