### ISSUE TITLE
Google signin returns exists:false

### ISSUE THREAD

**Issue by Deen-Abdultawab** [adrien2p/medusa-plugins#178]
After implementing the Google sign in, whenever I try to login with Google, I get a response from medusa that says exists:false. I followed the steps as suggested on the docs but no luck.

![Screenshot 2024-09-01 161725](https://github.com/user-attachments/assets/fd61d9a4-ea2e-4d12-b377-3630a46873c5)

**Comment by adrien2p** [comment]
this as been answered multiple times in already resolved issue, have you had a look in case it can help you? in the mean time I close this one
