### ISSUE TITLE
"Unable to verify authorization request state." during the passport.authenticate() 

### ISSUE THREAD

**Issue by Arsenalist** [adrien2p/medusa-plugins#46]
When using the Auth0 strategy and in production mode (sameSite = none as well), I get the following:

"Unable to verify authorization request state." during the passport.authenticate() 

I see that we added "state: true" as part of the strategy, and when I take that out I get

"Error: Scope "openid" is not allowed without Auth0Strategy state true"

This appears to work fine locally.

**Comment by Arsenalist** [comment]
I’ll do some more investigation and report back.

**Comment by Arsenalist** [comment]
I'm using medusa extender and modified `main.ts` with and it's still not working and getting the same error. I tried all combinations of `saveUninitialized` and `resave` as well. 

```
    expressInstance.use(
        session({
            proxy: true,
            secret: process.env.COOKIE_SECRET,
            resave:false,
            saveUninitialized: true,
            cookie: {
                sameSite: false,
                secure: true,
                maxAge: 1000 * 60 * 60 * 48,
                httpOnly: false,
            }
        })
    );
     expressInstance.set('trust proxy', 1);
        ```

**Comment by Arsenalist** [comment]
Opened a thread at [Auth0 community forums](https://community.auth0.com/t/unable-to-verify-authorization-request-state-auth0/98502).  I think we should hold off on releasing this feature until someone has got it working with cross-site cookies working.

**Comment by adrien2p** [comment]
In a production env, the sameSite is set to none, secure (cookie) is set to true. Since same site as to be none with secure cookie (all new browser expect that for security reason). And the trust is always set to 1. you can look into the medusa express loader to see those config.

**Comment by adrien2p** [comment]
> Opened a thread at [Auth0 community forums](https://community.auth0.com/t/unable-to-verify-authorization-request-state-auth0/98502). I think we should hold off on releasing this feature until someone has got it working with cross-site cookies working.

Nice 👍 I ll wait to see what is the output. I was about to release, just done the build and see this issue before releasing 😂

**Comment by Arsenalist** [comment]
yes, it doesn't work with sameSite = 'none' either.

Maybe you can test this with another app, but I can't get it to work.

When I check Auth0 logs I see a successful login, but `passport.authenticate()` in the router builder redirects to failureUrl with this message.

**Comment by Arsenalist** [comment]
Or at the very least if someone gets it working we can provide some guidance in the docs.

**Comment by adrien2p** [comment]
@juanzgc any thought on that one?

**Comment by juanzgc** [comment]
Just saw this issue, taking a look and will respond once I have some sort of solution

**Comment by adrien2p** [comment]
@Arsenalist @juanzgc have you checked that guys https://github.com/auth0/passport-auth0/issues/70#issuecomment-435711912

**Comment by Arsenalist** [comment]
> @Arsenalist @juanzgc have you checked that guys [auth0/passport-auth0#70 (comment)](https://github.com/auth0/passport-auth0/issues/70#issuecomment-435711912)

What key under session would I set that token in?

**Comment by adrien2p** [comment]
Have you try to use it locally and set the NODE_ENV=production on startup to see if you get something different. It would mean running under https as well. If it is a proxy issue and testing locally does not provide the error then we can confirm it is a proxy issue if the remote provider us a proxy on front of nodejs. Does that make sense?

**Comment by Arsenalist** [comment]
So I looked at it more and I finally was able to get this working, but I had to add the following to my main.ts:

```
    expressInstance.use(
        session({
            secret: process.env.COOKIE_SECRET,
            resave: true,
        })
    );
    ```

Once I added this, the message goes away. I think the root cause here was the cookie not being set, but this did it.

**Comment by adrien2p** [comment]
Might be worth checking if the same happen without the extender. In that case we might had a line in the doc no?

**Comment by Arsenalist** [comment]
> Might be worth checking if the same happen without the extender. In that case we might had a line in the doc no?

I can check, though I am pretty deep into extender at this point. Is there a way to skip using extender without removing it fro package.json?

**Comment by adrien2p** [comment]
Yes, you can run medusa develop directly and it will use the default entry file instead.

**Comment by Arsenalist** [comment]
It doesn't work with just `medusa develop` (when NODE_ENV is set to production).

In my case I'm on a Netlify front-end and a VPS hosting the backend. There are no proxies at play here.

**Comment by adrien2p** [comment]
What is your domain? Is it a custom one or the provider one with a sub domain

**Comment by Arsenalist** [comment]
It's a top-level domain. example.com. The app is located on api.example.com.

**Comment by adrien2p** [comment]
Ok so it is not one of the public suffix list

**Comment by Arsenalist** [comment]
Can we release this?
