### ISSUE TITLE
Error: Admin with email *** already exists

### ISSUE THREAD

**Issue by eparizzi-clevertech** [adrien2p/medusa-plugins#51]
I've just added the auth plugin with the default config for Auth0 shown in the [documentation](https://medusa-plugins.vercel.app/authentication/auth0).

This is my `user` table:

| id | email | first\_name | last\_name | api\_token | created\_at | updated\_at | deleted\_at | metadata | role | vendor\_id |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| usr\_01GQ82V74ZW9RXDQN2TPN7EJQD | admin@medusa-test.com | null | null | null | 2023-01-20 17:15:28.031860 +00:00 | 2023-01-20 17:15:55.377591 +00:00 | null | null | admin | null |
| usr\_01GQ82W1XEVFX8W0PVV8E0TZKT | magic@mushrooms.com | null | null | null | 2023-01-20 17:15:55.682478 +00:00 | 2023-01-20 17:15:55.682478 +00:00 | null | null | member | vendor\_01GQ82W1T7GK1ZE102AWGM05D1 |
| usr\_01GQ82W1XTEH4XT5HPE2EW5Y22 | tasty@truffles.com | null | null | null | 2023-01-20 17:15:55.700832 +00:00 | 2023-01-20 17:15:55.700832 +00:00 | null | null | member | vendor\_01GQ82W1TFEJWAKH3ZYT55SQD1 |

I've created an user in Auth0 with the email `magic@mushrooms.com`.
![image](https://user-images.githubusercontent.com/121125445/216038826-7cdb6406-d1a9-4461-af99-08eaff133241.png)

After signing in through Auth0 form, I get redirected to the admin callback (`/admin/auth/auth0/cb`) and the following error is displayed:

```
Error: Admin with email magic@mushrooms.com already exists
    at validateAdminCallback (E:\Work\Clevertech\Foraged\Repos\foraged-v3\backend\node_modules\medusa-plugin-auth\src\core\validate-callback.ts:37:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Auth0AdminStrategy.validate (E:\Work\Clevertech\Foraged\Repos\foraged-v3\backend\node_modules\medusa-plugin-auth\src\auth-strategies\auth0\admin.ts:47:23)
    at async callback (E:\Work\Clevertech\Foraged\Repos\foraged-v3\backend\node_modules\medusa-plugin-auth\src\core\passport\Strategy.ts:19:29)
```

The documentation says the default behaviour is as follows:

- for the admin
  - if the user trying to authenticate exists
then we are looking in the metadata to find if any other external authentication methods have been used. If none are found, then the user gets authenticated and can proceed and the metadata gets updated. In the case another external authentication method have been used in the past, then an unauthorized will be returned. If you want to allow a user to use multiple external authentication methods, you can update his metadata
  - if the user trying to authenticate does not exist, an unauthorized error will be returned

The metadata column for this user is null and it's not clear what the plugin is expecting here... 

"If you want to allow a user to use multiple external authentication methods, you can update his metadata" .- How?

For reference, we're looking to exclusively use Auth0 for signing so we don't need to support Medusa's default authentication as well. So if all users and customers will be signing in through Auth0, what do we need to set in the `metadata` column for it to work?

**Comment by adrien2p** [comment]
In fact there is an error in the behaviour description indeed. I ll intend to update it asap. 

To avoid any security issues, you have to add in the user metadata { 'authProvider': 'auth0.admin.medusa-auth-plugin' }
