### ISSUE TITLE
How to manage failureRedirect when there is no login page

### ISSUE THREAD

**Issue by tsvetann** [adrien2p/medusa-plugins#80]
Hi and thanks for this library. I am a bit unsure how to configure failureRedirect config (medusa-plugin-auth with google), when I don't really have a login page. On my website the login functionality comes as a pop-up available on every page. How would you advise me to configure failureRedirect?

Thanks

**Comment by adrien2p** [comment]
Maybe you could handle a query params that you client will use to show the pop up?
