### ISSUE TITLE
Users are not logged out of Auth0 when logging out through medusa

### ISSUE THREAD

**Issue by abmenzel** [adrien2p/medusa-plugins#85]
I noticed that after logging out from Medusa and logging back in through Auth0, users are returned to an OTP prompt (if using MFA) instead of having to specify email + password.

It seems that users are not logged out of auth0.
I think we would have to implement this step: https://auth0.com/docs/authenticate/login/logout/log-users-out-of-auth0#logout_hint
Or maybe I am missing something?

I would like to have a go at creating a PR for this, but I would love some feedback on how to approach it @adrien2p

**Comment by adrien2p** [comment]
If I am right, the pr should include a custom logout route that would logout the user from the provider he as connected with and then apply the core logout. wdyt?
