### ISSUE TITLE
CORS issue but the rest of Medusa backend works

### ISSUE THREAD

**Issue by rasmuslian** [adrien2p/medusa-plugins#86]
Hi,
I am facing an issue with plugin when moving from local development to a Railway server. I am using the plugin for authenticating admin users with Firebase. The plugin works as expected in my local environment but now when I have deployed my site and Medusa backend to Railway I receive this error:

❌  "Access to XMLHttpRequest at 'https://<medusa-backend>.up.railway.app/admin/auth/firebase' from origin 'https://<my-domain>.up.railway.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource."

And got a "Referrer Policy: strict-origin-when-cross-origin" when inspected the network request.

I have added these environment variables in Railway:
BACKEND_URL=https://<medusa-backend>.up.railway.app
ADMIN_URL=https://<medusa-backend>.up.railway.app
STORE_URL=https://<my-domain>.up.railway.app

I've also tried to add https://<medusa-backend>.up.railway.app and https://<my-domain>.up.railway.app to the Authorised Domains in Firebase Authentication with no success.

The rest of Medusa works fine with no CORS issues.

**Comment by adrien2p** [comment]
@dPreininger could you have a look at this please 😍

**Comment by dPreininger** [comment]
@rasmuslian I believe the cause for this is that the url is incorrect. You have a dot right after https://. Try urls without this dot like so: https://up.railway.app.

**Comment by rasmuslian** [comment]
> any news @rasmuslian

Sorry for late reply, I’ve gone on vacation today and will be afk for the next 1.5 weeks. Will update after that.

**Comment by rasmuslian** [comment]
@adrien2p However when looking at this now I see that my urls in the question are wrong, they are not https://.up.railway.app but it should be for example BACKEND_URL=https://medusa-server.up.railway.app and STORE_URL=https://my-frontend.up.railway.app

**Comment by rasmuslian** [comment]
@adrien2p @dPreininger Hi again, I’m now back from vacation, any updates? See my previous answer also :)

**Comment by rasmuslian** [comment]
Update: I tested and redeployed the whole thing, turns out that probably I mis-set the environment variables after all somehow. Sorry for all the confusion, closing now.
