### ISSUE TITLE
Cannot register if order is made as guest

### ISSUE THREAD

**Issue by FaZeRs** [adrien2p/medusa-plugins#93]
[medusa-plugin-auth](https://github.com/adrien2p/medusa-plugins/tree/main/packages/medusa-plugin-auth)
I'm receiving `Internal Server Error` if I'm trying to register after I have made an order without registration

```
﻿Error: Guest customer with email already exists
﻿at CustomerService.<anonymous> (/app/node_modules/@medusajs/medusa/dist/services/customer.js:419:55)
﻿at step (/app/node_modules/@medusajs/medusa/dist/services/customer.js:59:23)
﻿at Object.next (/app/node_modules/@medusajs/medusa/dist/services/customer.js:40:53)
﻿at fulfilled (/app/node_modules/@medusajs/medusa/dist/services/customer.js:31:58)
﻿at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
﻿```

**Comment by adrien2p** [comment]
The current behaviour is that if no validated account exists then we try to create the customer, maybe we can change that to just check if any accounts exists with the email?

**Comment by FaZeRs** [comment]
I think this error is because `password` field is missing. When I try to register using signup form it works.

https://github.com/medusajs/medusa/blob/develop/packages/medusa/src/services/customer.ts#L328

**Comment by adrien2p** [comment]
I will be 3 weeks away and tried to relax a bot, maybe if you could ipen a pr if you feel something can be done as a proposal so i can look at it when i am free, would you be keen to do that @FaZeRs ? 😍

**Comment by FaZeRs** [comment]
@adrien2p as I see alternative would be to create method in auth plugin which does the input data validation and creates customer using `CustomerRepository`. Maybe you have got any other ideas?

**Comment by adrien2p** [comment]
Did you find a solution for your case?
