### ISSUE TITLE
how to handle strict mode?

### ISSUE THREAD

**Issue by tsvetann** [adrien2p/medusa-plugins#94]
Thanks for this plugin! The default behaviour of the plugin works well so far and as part of the design if a user has already registered with email + pass this plugin does not allow login with social media. If I understand correctly I can change the behaviour with strict mode? Is there any guidance or example how to do that? Thanks

**Comment by adrien2p** [comment]
The strict option alter the default behaviour described in the doc. It makes possible for a user to login with a different provider even though the default behaviour is protecting against it for security reason
