### ISSUE TITLE
Can't add google auth

### ISSUE THREAD

**Issue by akhad7799** [adrien2p/medusa-plugins#95]
@adrien2p 
I did the same as mentioned on medusa-plugin-auth documentation to add google auth to medusa application.
But got some error. Tell me if I'm missing something here 

**Error:**

<img width="566" alt="image" src="https://github.com/adrien2p/medusa-plugins/assets/55797133/1fbf1997-1caf-4267-b017-7416a142a610">

<img width="475" alt="image" src="https://github.com/adrien2p/medusa-plugins/assets/55797133/d32458bd-6b5c-464b-a46d-f280b84a3be7">

**This is my Google Client**

<img width="623" alt="image" src="https://github.com/adrien2p/medusa-plugins/assets/55797133/847d1e6f-79b2-4ba4-909b-fc8802f0031b">

**Comment by HalimACeylan** [comment]
you should rewrite this part like that :  
``` const BACKEND_URL = process.env.BACKEND_URL || "http://localhost:9000"
const ADMIN_URL = process.env.ADMIN_URL || "http://localhost:7000"
const STORE_URL = process.env.STORE_URL || "http://localhost:8000" ```

**Comment by HalimACeylan** [comment]
you should rewrite this part like that : 
```
const BACKEND_URL = process.env.BACKEND_URL || "http://localhost:9000"
const ADMIN_URL = process.env.ADMIN_URL || "http://localhost:7000"
const STORE_URL = process.env.STORE_URL || "http://localhost:8000"
```

**Comment by adrien2p** [comment]
I ll close this ticket and reopen it if you still Encounter the issue
