### ISSUE TITLE
Feedback for “Index”

### ISSUE THREAD

**Issue by sagi-ekstein** [adrien2p/medusa-plugins#96]
Hi,
firstly, thank you for the auth plugin. I have an issue with it I hope you came across. 
When enabled, normal auth (user/pass) does not work any longer. only Social auth is working (google/facebook). 
if I disable the plugin, normal login works. 
I am sure I am missing something, I hope you can help.

**Comment by adrien2p** [comment]
Which version are you using? It shouldn't interfere with the other auth from the core as they are other passport strategies

**Comment by sagi-ekstein** [comment]
Medusa 1.6.2
and Auth 1.2.1

**Comment by adrien2p** [comment]
I suggest you to upgrade your medusa and auth package as you have old versions of them
