### ISSUE TITLE
Login Success but still 401

### ISSUE THREAD

**Issue by hukhho** [adrien2p/medusa-plugins#97]
when i login with google, it already success, but when it return to admin dashboard it have 401, already go to localhost:7001/a/products but then it go to 401, how i can login to admin dashboard with google?
![image](https://github.com/adrien2p/medusa-plugins/assets/41692399/3df6aee4-53f5-4fce-9896-3e929c48f767)
![image](https://github.com/adrien2p/medusa-plugins/assets/41692399/2b676e70-f0ad-4f26-a430-5934d05c0f7e)

**Comment by adrien2p** [comment]
Can you share more info like the packages versions please

**Comment by hukhho** [comment]
"dependencies": {
    "@medusajs/admin": "^7.1.1",
    "@medusajs/cache-inmemory": "^1.8.8",
    "@medusajs/cache-redis": "^1.8.8",
    "@medusajs/event-bus-local": "^1.9.6",
    "@medusajs/event-bus-redis": "^1.8.9",
    "@medusajs/file-local": "^1.0.2",
    "@medusajs/icons": "^1.0.0",
    "@medusajs/medusa": "^1.17.0",
    "@medusajs/ui": "2.0",
    "@medusajs/ui-preset": "^1.0.1",
    "@tanstack/react-query": "4.22.0",
    "babel-preset-medusa-package": "^1.1.13",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "dotenv": "16.0.3",
    "express": "^4.17.2",
    "medusa-fulfillment-manual": "^1.1.38",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.24",
    "medusa-payment-stripe": "^6.0.4",
    "medusa-plugin-auth": "^1.6.0",
    "medusa-react": "^9.0.6",
    "prism-react-renderer": "^2.0.4",
    "typeorm": "^0.3.16"
  }

**Comment by adrien2p** [comment]
The plugin is not yet compatible with medusa 1.17 @dPreininger was keep to open a pr to make it compatible since he has worked on the auth update 👌

**Comment by adrien2p** [comment]
Basically, the current plugin version generates the token as it was expected by the previous versions of medusa. I have no access to my laptop for now but it is just a matter of adjusting this part.

**Comment by mortenengel** [comment]
@adrien2p we are having trouble with this bug as well - I tried having a look into the code to see if I could make a PR, but I haven't been able to identify where the headers need changed.

Do we have any ETA on when this can be looked into? Or can you guide me on where this change needs to be implemented?

**Comment by adrien2p** [comment]
There is a pr open, i am just quite busy at the moment. The pr will make it compatible with medusa 1.7

**Comment by adrien2p** [comment]
Could you try the latest please

**Comment by mortenengel** [comment]
@adrien2p looks to be working perfectly for me! Good job.
